openapi: 3.0.0
info:
  title: Series API
  version: 1.0.0
servers:
  - url: http://localhost:8080/api
paths:
  /series:
    get:
      summary: Obtener todas las series
      responses:
        '200':
          description: Lista de series
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Serie'
    post:
      summary: Crear una nueva serie
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Serie'
      responses:
        '200':
          description: Serie creada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Serie'

  /series/{id}:
    get:
      summary: Obtener una serie por ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Serie encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Serie'
        '404':
          description: No encontrada
    put:
      summary: Actualizar una serie
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Serie'
      responses:
        '200':
          description: Serie actualizada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Serie'
    delete:
      summary: Eliminar una serie
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Eliminada

  /series/{id}/status:
    patch:
      summary: Actualizar el estado de una serie
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
      responses:
        '200':
          description: Estado actualizado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Serie'

  /series/{id}/episode:
    patch:
      summary: Incrementar episodio
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Episodio actualizado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Serie'

components:
  schemas:
    Serie:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        status:
          type: string
        lastEpisodeWatched:
          type: integer
        totalEpisodes:
          type: integer
        ranking:
          type: integer
